### ISSUE TITLE
Backpacks stop working.

### ISSUE THREAD

**Issue by Memphizzz** [LaserHydra/Backpacks#2] opened 2019-09-10 20:37 UTC
Hi there,

first of all, thank you very much for this great plugin! Our players love it!
Unfortunately, for some players it just stops working and they have to log out and in again to make it work again.
A server-side reload of the plugin works as well in those cases and they can use it again without having to relog.
Is there anything we can provide for you to identify this problems, the next time this happens?

Thanks again for all the work you've put into the creation and maintenance of this plugin!

Regards,

MemphiZ

**Comment by KaidenP** [comment] 2020-03-23 16:00
I also experience this issue, and I'm pretty sure [Backpacks.cs#L611](https://github.com/LaserHydra/Backpacks/blob/9fa44787c5d3eeff9cd0eb5024d46f54f1ef92d2/Backpacks.cs#L611) is to blame

**Comment by WheteThunger** [comment] 2020-06-20 23:19
I am able to consistently reproduce this issue with the following steps.
1. Open the backpack
2. Disconnect from server
3. Die while offline
4. Reconnect to server and try to open backpack (spoiler: it won't open)

On my local test server, this is usually fixed by reconnecting. However, on a server I frequent, sometimes reconnecting even several times does not fix it, but it eventually fixes itself for reasons unknown. Edit: It turns out this is because that server has the `SaveBackpacksOnServerSave` configuration variable set to `true`. With that setting, borked backpacks periodically gets fixed when the server saved based on `server.saveinterval`, which defaults to 600 seconds (10 minutes).

I added some log statements and tested locally to determine this is where the `Backpack.Open()` method exits early with the reproduction steps above.

https://github.com/LaserHydra/Backpacks/blob/9fa44787c5d3eeff9cd0eb5024d46f54f1ef92d2/Backpacks.cs#L621-L628

By adding more logging, I determined that the `_itemContainer.entityOwner` is null, though I don't understand why.

**What happens while dying offline to cause the backpack to stop working?**

The logic in the `OnPlayerDisconnected()` hook kills the container completely and seems to work fine.

https://github.com/LaserHydra/Backpacks/blob/9fa44787c5d3eeff9cd0eb5024d46f54f1ef92d2/Backpacks.cs#L122-L137

However, when the player dies while offline, the `OnEntityDeath()` hook **reconstructs** the `Backpack` instance with `Backpack.Get()`, and does not fully clean it up afterward.

https://github.com/LaserHydra/Backpacks/blob/9fa44787c5d3eeff9cd0eb5024d46f54f1ef92d2/Backpacks.cs#L182-L200

I theorized that when the backpack is reconstructed, if the player is offline, the `entityOwner` will be null. However, logging has proven otherwise. All I can tell is that sometime between when the backpack is constructed and when the player tries to open the backpack after reconnecting, the `entityOwner` has been nulled out, leading to the backpack not opening.

I have spent significant time attempting to fix (or work around) this issue, but unfortunately every solution that comes to mind seems like it could cause other problems. This plugin has several configuration variables (`DropOnDeath`, `EraseOnDeath`, and `SaveBackpacksOnServerSave`) that change the behavior of the plugin, making it difficult for me to reason about all of the possible end-to-end test cases to ensure I don't introduce a new issue in my patch.

@LaserHydra Can you advise on test cases to perform to make sure I don't introduce a regression for all of the possible configurations?

**Comment by LaserHydra** [comment] 2020-06-28 13:29
Thank you again for contributing and providing such an elaborate bug description.
Indeed one has to be careful not to introduce new bugs. Looking at your PR https://github.com/LaserHydra/Backpacks/pull/7 though, I would say that is probably the safest way to handle this, instead of dealing with unload and or saving the file again at a different place.

For testing that the different configurations work correctly, one can only really try out all the different options.
I.e. modify the backpack and make sure it only saves when it's supposed to. Die with a backpack and make sure the backpack is dropped or erased based on the configuration.

Looking at your suggested solution though, I am quite sure it wouldn't introduce any change to how different configurations are handled. I'll also comment on that PR directly.

**Comment by LaserHydra** [comment] 2020-08-02 13:07
https://github.com/LaserHydra/Backpacks/pull/7 was merged which should fix this issue.
It will be part of the upcoming release.

**Closed as completed by LaserHydra** 2020-08-02 13:07 UTC
